### PR TITLE
DLS-8635: Updated README and build configuration

### PR DESCRIPTION
**Pull request by johno1985**

### CODE REVIEW

**Comment by johno1985** [comment]
rebuild

**Comment by johno1985** [comment]
rebuild

**Comment by johno1985** [comment]
rebuild

**Review by LAJW — CHANGES_REQUESTED** [review]
The PR doesn't change any API calls.

**Comment by johno1985** [comment]
> 

The API call change will be done in a separate PR

**Review by karolina-zaborska — APPROVED** [review]

**Review by LAJW — APPROVED** [review]
Thank you for changing the title.

**Pull request merged**
